FROM docker.io/library/python:3.11-slim-bullseye

WORKDIR /app
COPY . /app/

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install

ENTRYPOINT ["poetry", "run", "trailblazer"]
