"""add priority field to pick up qos setting

Revision ID: 0829dd9c54d7
Revises: fcc3ed539387
Create Date: 2017-05-17 16:11:37.988826

"""

# revision identifiers, used by Alembic.
revision = "0829dd9c54d7"
down_revision = "fcc3ed539387"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis",
        sa.Column("priority", sa.Enum("low", "normal", "high"), nullable=True),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis", "priority")
    ### end Alembic commands ###
