"""add user management

Revision ID: 4f4098ada28f
Revises: 8786470f3a1b
Create Date: 2016-11-10 09:49:32.692969

"""

# revision identifiers, used by Alembic.
revision = '4f4098ada28f'
down_revision = '8786470f3a1b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
