"""add is_visible and new status option

Revision ID: 61df280b0af6
Revises: 65a2be59adb1
Create Date: 2016-09-30 10:03:38.801619

"""

# revision identifiers, used by Alembic.
revision = "61df280b0af6"
down_revision = "65a2be59adb1"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.orm import sessionmaker

from trailblazer.store.models import Analysis

Session = sessionmaker()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("is_visible", sa.Boolean(), nullable=True))
    ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)

    op.execute(
        """
      UPDATE trailblazer.analysis
      SET is_visible=1;
    """
    )
    with bind.begin() as transaction:
        for run in session.query(Analysis).filter_by(status="failed"):
            case_runs = (
                session.query(Analysis)
                .filter_by(case_id=run.case_id)
                .order_by(Analysis.logged_at.desc())
            )
            if case_runs.first().status == "completed":
                run.is_visible = False
        transaction.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis", "is_visible")
    ### end Alembic commands ###
