"""add another status option for (human) error

Revision ID: 65a2be59adb1
Revises: afffbd40f0c3
Create Date: 2016-08-31 08:26:03.085693

"""

# revision identifiers, used by Alembic.
revision = "65a2be59adb1"
down_revision = "afffbd40f0c3"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
