"""add Metadata table

Revision ID: 79f5f7602ba5
Revises: 92599c4afa62
Create Date: 2016-08-18 12:50:38.315130

"""

# revision identifiers, used by Alembic.
revision = '79f5f7602ba5'
down_revision = '92599c4afa62'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    ### end Alembic commands ###
