"""initial revision
Revision ID: 84079287ee2f
Revises:
Create Date: 2016-08-17 16:05:03.221966
"""

# revision identifiers, used by Alembic.
revision = "84079287ee2f"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
