"""add failed_step to unique contraint with default

Revision ID: 92599c4afa62
Revises: 3140747f399a
Create Date: 2016-08-18 08:48:05.972262

"""

# revision identifiers, used by Alembic.
revision = "92599c4afa62"
down_revision = "3140747f399a"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u"_uc_case_start_status_step", "analysis", type_="unique")
    op.create_unique_constraint(
        "_uc_case_start_status_step", "analysis", ["case_id", "started_at", "status", "failed_step"]
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_uc_case_start_status_step", "analysis", type_="unique")
    op.create_unique_constraint(
        u"_uc_case_start_status_step", "analysis", ["case_id", "started_at", "status"]
    )
    ### end Alembic commands ###
