"""add step table, store all error steps

Revision ID: a820403d11af
Revises: fcc3ed539387
Create Date: 2016-11-22 08:39:22.461995

"""

# revision identifiers, used by Alembic.
revision = 'a820403d11af'
down_revision = 'fcc3ed539387'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=128), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('elapsed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('failed', 'cancelled', 'timeout'), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], [u'analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    ### end Alembic commands ###
