"""add another option for status field

Revision ID: afffbd40f0c3
Revises: 2029c2789209
Create Date: 2016-08-23 10:07:37.799154

"""

# revision identifiers, used by Alembic.
revision = 'afffbd40f0c3'
down_revision = '2029c2789209'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
