"""add user link to runs

Revision ID: fcc3ed539387
Revises: b26bb11641b4
Create Date: 2016-11-18 20:24:51.517043

"""

# revision identifiers, used by Alembic.
revision = "fcc3ed539387"
down_revision = "b26bb11641b4"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "analysis", "user", ["user_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "analysis", type_="foreignkey")
    op.drop_column("analysis", "user_id")
    ### end Alembic commands ###
