COMPLETED_STATUS = "completed"
FAILED_STATUS = "failed"
ONGOING_STATUSES = ("pending", "running", "error")
STARTED_STATUSES = ["completed", "failed", "pending", "running", "error"]
NORMAL_CATEGORIES = ("COMPLETED", "RUNNING", "PENDING")
FAILED_CATEGORIES = ("FAILED", "CANCELLED", "TIMEOUT")
CATEGORIES = NORMAL_CATEGORIES + FAILED_CATEGORIES
STATUS_OPTIONS = ("pending", "running", "completed", "failed", "error", "canceled")
JOB_STATUS_OPTIONS = [category.lower() for category in CATEGORIES]
PRIORITY_OPTIONS = ("low", "normal", "high")
TYPES = ("wes", "wgs", "rna", "panel")
