name: Black

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - uses: psf/black@stable
        with:
          options: ". --check --line-length 100"
