name: Black

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: psf/black@stable
        with:
          options: ". --check --line-length 100"
