name: Build and publish CLI image for branch

on:
  push:
    branches-ignore:
      - "master"

jobs:
  docker-image-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create tags
        id: create_tags
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr "/" "-")
          TAGS="clinicalgenomics/trailblazer-cli:$BRANCH_NAME"
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile-cli
          push: true
          tags: ${{ env.TAGS }}
