name: Build and publish image on new release event

on:
 release:
  types:
   - created

jobs:
  docker-image-release_push:
    # Push to Docker Hub when a new release is created
    runs-on: ubuntu-latest
    steps:

     - name: Check Out Repo
       uses: actions/checkout@v4

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build image for web API
       uses: docker/build-push-action@v6
       with:
         context: ./
         file: ./Dockerfile
         push: true
         tags: "clinicalgenomics/trailblazer:${{github.event.release.tag_name}}, clinicalgenomics/trailblazer:latest, clinicalgenomics/trailblazer-stage:${{github.event.release.tag_name}}"

     - name: Build image for CLI
       uses: docker/build-push-action@v6
       with:
         context: ./
         file: ./Dockerfile-cli
         push: true
         tags: "clinicalgenomics/trailblazer-cli:${{github.event.release.tag_name}}, clinicalgenomics/trailblazer-cli:latest"
