name: Production install

on: ["pull_request"]

jobs:

  production-install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Test install
      run: |
        pip install pip --upgrade pip
        pip install .
        pip check
    - name: Test install dev
      run: |
        pip install . -r requirements-dev.txt
        pip check
        pytest
