name: scan image
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name and remove illegal chars
        id: get_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo "$(tr "/" "-" <<<${GITHUB_REF#refs/heads/})")"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "clinicalgenomics/trailblazer-stage:${{steps.get_branch_name.outputs.branch}}"
          format: "sarif"
