name: Test coverage

on: [push]

jobs:

  tests-coverage:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Trailblazer
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt

    - name: Coveralls Dependencies
      run: |
        pip install pytest-cov coveralls

    - name: Test with pytest & Coveralls
      run: |
        pytest --cov=trailblazer/
        coveralls --service=github
      env:
        GITHUB: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
