name: TB CI

on: [push]

jobs:

  tests-coverage:

    runs-on: ubuntu-20.04

    steps:

    # Check out Trailblazer code
    - uses: actions/checkout@v2.5.0

    # Set up python
    - name: Set up Python 3.7
      uses: actions/setup-python@v4.3.1
      with:
        python-version: 3.7

    - name: TB Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt

    - name: Coveralls Dependencies
      run: |
        pip install pytest-cov coveralls

    - name: Test with pytest & Coveralls
      run: |
        pytest --cov=trailblazer/
        coveralls --service=github
      env:
        GITHUB: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
