name: Test coverage

on: [push]

jobs:

  tests-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Test with Pytest & Coveralls
      run: |
        poetry run pytest --cov=trailblazer/
        poetry run coveralls
      env:
        GITHUB: 1
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  finish:
    needs: tests-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
